# CNC Laser Burn Config

laser_power = 192 # scale of 0-255

# 75 % = 192 ;  80 % = 204
# 85 % = 217 ;  90 % = 230
# 95 % = 243 ; 100 % = 255

travel_speed = 500 # all speeds in mm/m

# Outline
has_outline = true
outline_speed = 60

# Infill
has_infill = true
infill_speed = 60

density = 5 # lines per mm, can be one of 10, 5, 2, or 1
