# CNC Laser Burn Config

# Notes:
#   Laser Power is a percentage
#   All speeds are in mm/m
#   Density is measured in lines per mm

# How large your piece of wood is, in mm

print_height = 100
print_width = 100

# Accepted Laser Power Range:
#  50% -> 100% : 75% default

laser_power = 75

# Accepted Speed Ranges:
#  Travel  : 400 -> 750 : 500 default
#  Outline :  40 ->  80 :  60 default
#  Infill  :  40 ->  80 :  60 default

travel_speed = 500

has_outline = true
outline_speed = 60

has_infill = true
infill_speed = 60

# Accepted Density Values:
#   10, 5, 2, or 1 : 5 default

density = 5
