name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ConorMacBride/install-package@v1
      with:
        brew: imagemagick
    - name: make
      run: make all
